title: sizeof
name: sizeof # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Display the exact size of the specific file(s) in the passed argument(s) # 79 char long summary
description: |
  This is a simple application that tells you the size of the files
  you specify and if no file is found it safely skips over them with
  a simple indication that it didn't find that file.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  sizeof:
    plugin: cmake
    source-type: git
    source: https://github.com/iInvisibilities/sizeof

platforms:
  amd64:

apps:
  sizeof:
    command: bin/sizeof
